### ISSUE TITLE
Windows Install - controller.py: Could not find module 'libpulse.so.0'

### ISSUE THREAD

**Issue by amercer86** [Staacks/inkkeys#10]
Hey gang - I'm getting this set up on my Windows 11 pc running Python 3.9. Initially I found that I was missing the pulsectl dependency but, after installing via pip, I now get this error:

`FileNotFoundError: Could not find module 'libpulse.so.0' (or one of its dependencies). Try using the full path with constructor syntax.`

As far as I can tell, libpulse is part of pulsectl so I don't know what else to try. Hoping you guys might know whats up. Thanks!

**Comment by Staacks** [comment]
Pulseaudio is a sound server for Linux. It is only used for the volume control function as one of the toggles of the knob. So, you can either remove the module entirely (and few function calls for that module) and replace it with your own mappings or you will have to replace it with a Windows equivalent.

**Comment by amercer86** [comment]
Well that explains it! :)

I don't actually need or want volume control as I already have a dedicated wheel on my keyboard. I commented out import pulsectl and it seems to be fine. I also just now realized this issue has already been covered in post #5 . Sorry about the duplicate!
